---
title: "01-DatosOrdinales"
author: "Adrian"
date: "16/1/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Datos Ordinales

```{r}
crabs = read.table("../../../data/datacrab.txt", header = T)
# Omitir la primera columna que es un index
crabs = crabs[,-1]
str(crabs)
# Anchura de los cangrejos
table(crabs$width)

# Dividimos la anchura de los cangrejos en niveles
intervalos = cut(crabs$width, breaks = c(21,25,29,33,Inf), right = FALSE, labels = c("21-25", "25-29", "29-33", "33-..."))

crabs$width.rank = ordered(intervalos)
str(crabs)

tabla = table(crabs[,c(1,6)])
tabla

# Frecuencia relativa 
Fr.rel = round(prop.table(tabla, margin = 1),3)
Fr.rel
# Frecuencia relativa acumulada
Fr.rel.acu = round(apply(prop.table(tabla, margin = 1), MARGIN = 1, FUN = cumsum),3)
t(Fr.rel.acu)

azul = c("cyan", "cyan4", "cyan1", "cyan3")
# Diagrama de frecuencias relativas
barplot(t(Fr.rel), beside = T, legend = T, ylim = c(0,1), col = azul,
        main = "diagrama de barras de frecuencias relativas",
        args.legend = list(x = "topright", cex=0.55))

# Diagrama de frecuencias relativas acumuladas
barplot(Fr.rel.acu, beside = T, legend = T, ylim = c(0,1), col = azul,
        main = "diagrama de barras de frecuencias relativas",
        args.legend = list(x = "topleft", cex=0.55))

```

