---
title: "02-Variables aleatorias discretas"
author: "Adrian"
date: "21/1/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Variable aleatoria discreta
- Variable aleatoria discreta: $\Omega \Longrightarrow R$ es discreta cuando $D_x$ es finito o un subconjunto de $N$

- Funcion de densidad: Es la funcion $f : R \Longrightarrow [0, 1]$ definida por $$f(x) = p(X = x)$$

Notese que $f(x) = 0$ si $x \notin D_X$. Por tanto, interpretaremos la funcion de densidad como la funcion $$f : D_x \Longrightarrow [0,1]$$


### Esperanza
- Esperanza de una v.a. discreta: Sea $f: D_x \Longrightarrow[0, 1]$ la densidad de X, entonces la esperanza respecto de la densidad es la suma ponderada de los elementos de Dx, multiplicando cada elemento x de $D_x$ por su probabilidad.

### Varianza 
- Varianza de una v.a. discreta: Sea $f: D_x \Longrightarrow[0, 1]$ la densidad de X, entonces la varianza respecto de la densidad es el valor esperado de la diferencia al cuadrado entre X y su valor medio $E(X)$,
$$Var(x) = E((X - E(X))^2)$$

### Desviacion tipica
- Desviacion tipica de una v.a. discreta: Sea $f: D_x \Longrightarrow[0, 1]$ la densidad de X, entonces la desviacion tipica respecto de la densidad es 
$\alpha(X) = \sqrt{Var(X)}$








