---
title: "Data Frames"
author: "Adrian"
date: "14/1/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Frames
#### Es una tabla de doble entrada, formada por variables en las 
#### columnas y observaciones de estas variables en filas.
- data() -> Abrir una ventana con la lista de los objetos de datos
  a los que tenemos acceso en la sesión actual de R

### Data Frame de Iris
```{r}
df = iris
# Obtener las 5 primeras y 5 ultimas lineas
head(df, 5)
tail(df, 5)
# Obtener la estructura general del data frame
str(df)
# Obtener las columnas del data frame
names(df) 
colnames(df)
# Obtener las filas del data frame
rownames(df)
# Lista con filas y columnas del data frame
dimnames(df)
# Consultar numero de filas
nrow(df)
# Consultar numero de columnas
ncol(df)
# Consultar numero de columnas y filas
dim(df)
# Obtener valores de una columna
df$Petal.Length[1:10]
```

### Sub-data frames. Acesso al DF
```{r}
# Obtener las 10 primeras filas
df[1:10, ]
# Obtener filas con condicionales
df[df$Species == "setosa" & df$Sepal.Width>4, ]
# Obtener filas 1 y 3 con las columnas 2 y 5
df[df$Species == "setosa" & df$Sepal.Width>4, ][c(1,3), c(2,5)]
```
























